-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Npc_Workspace:FindFirstChild("Sword Sellers").Katana
}

game:GetService("ReplicatedStorage").Replication.ClientEvents.BuySword:InvokeServer(unpack(args))
