-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Claim",
    [2] = 3
}

game:GetService("ReplicatedStorage").RemoteFunctions.RequestPlaytimeReward:InvokeServer(unpack(args))
